---
include:
  # Lewa połowa (central) – ZMK Studio przez USB
  - board: nice_nano//zmk
    shield: dactyl_manuform_6x6_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # Prawa połowa (peripheral)
  - board: nice_nano//zmk
    shield: dactyl_manuform_6x6_right
  # Reset ustawień BLE (jednorazowo)
  - board: nice_nano//zmk
    shield: settings_reset
