---
include:
  # Lewa połowa (peripheral)
  - board: nice_nano/nice_nano/zmk
    shield: dactyl_manuform_6x6_left
  # Prawa połowa (central) – ZMK Studio przez USB
  - board: nice_nano/nice_nano/zmk
    shield: dactyl_manuform_6x6_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # Reset ustawień BLE (jednorazowo)
  - board: nice_nano/nice_nano/zmk
    shield: settings_reset
